_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/app/adapteacher/checkpoint/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    RES5_DILATION: 2
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 10
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 100000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.04
  AMP:
    ENABLED: true
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("bdd100k_day_train",) #voc_2012_train
  TRAIN_UNLABEL: ("bdd100k_night_train",) #Clipart1k_train
  TEST: ("bdd100k_night_val",) #Clipart1k_test
SEMISUPNET:
  Trainer: "ateacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 50000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.3
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4"
  DIS_LOSS_WEIGHT: 0.05
TEST:
  EVAL_PERIOD: 2000