_BASE_: ./Base-RCNN-C4.yaml
MODEL:
  META_ARCHITECTURE: DAobjTwoStagePseudoLabGeneralizedRCNN
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  MASK_ON: false
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: PseudoLabRPN
  ROI_HEADS:
    NAME: StandardROIHeadsPseudoLab
    LOSS: CrossEntropy
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: FastRCNNConvFCHead
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: WarmupTwoStageMultiStepLR
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 100000
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 100
DATASETS:
  CROSS_DATASET: true
  TRAIN_LABEL: ("voc_2012_trainval",)
  TRAIN_UNLABEL: ("Clipart1k_train",)
  TEST: ("Clipart1k_test",)
SEMISUPNET:
  Trainer: ateacher
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 60000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 0.5
  SUP_LOSS_WEIGHT: 1
  DIS_TYPE: res4
  DIS_LOSS_WEIGHT: 0.1
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: ./output/faster_rcnn_R101_cross_clipart_test